# Generated by Django 5.2.1 on 2025-06-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='otp',
            field=models.IntegerField(default=123456),
            preserve_default=False,
        ),
    ]
